# Generated by Django 5.1.1 on 2024-09-30 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceoEmpresa', to=settings.AUTH_USER_MODEL)),
                ('funcionarios', models.ManyToManyField(blank=True, related_name='funcionariosFk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceoEmpresa', to='posts_app.empresa')),
                ('participantes', models.ManyToManyField(blank=True, related_name='participanteProjeto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
