# Generated by Django 5.1.1 on 2024-10-01 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_empresa_projeto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='Empresa',
            new_name='empresas',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='funcionarios',
        ),
        migrations.AddField(
            model_name='projeto',
            name='criador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='projetosCriados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
