# Generated by Django 5.1.1 on 2024-10-01 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_rename_empresa_projeto_empresas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='funcionarios',
            field=models.ManyToManyField(blank='true', related_name='funcionariosEmpresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
