# Generated by Django 5.1.1 on 2024-10-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0004_empresa_funcionarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='participantes',
            new_name='membros',
        ),
    ]
